org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
fabric.loom.disableMinecraftVerification=true

# Fabric Properties
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e0778a3
loader_version=0.18.6

# Mod Properties
mod_version=3.2.2+stapi
maven_group=sunsetsatellite
archives_base_name=retrostorage
#	modrinth_slug=template
#	modrinth_version_name=Template

# Dependencies
stapi_version=2.0.0-alpha.6
glass_networking_version=1.0.7
gcapi_version=3.2.5
alwaysmoreitems_version=1.9.0-alpha.6
modmenu_version=1.1.1
bhcreative_version=0.4.9
spawneggs_version=1.11.0
retrocommands_version=0.5.10
retroauth_version=1.1.1
unitweaks_version=0.27.0
nyalib_version=0.20.1
whatsthis_version=1.0.0-rc8
uniwrench_version=2.8.0
debugutilities_version=1.0.0-alpha.1