org.gradle.jvmargs=-Xmx2G

# BTA
bta_version=7.2-pre1

# Loader
loader_version=0.15.6-babric.6-bta

# HalpLibe
halplibe_version=4.0.6
catalyst_main_version=1.6.0
catalyst_secondary_version=1.5.0
btwaila_version=1.1.1-7.2-pre1
dragonfly_version=1.5.0-7.2-pre1

# Mod
mod_version=2.0.1
mod_group=sunsetsatellite
mod_name=retrostorage
