pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Jitpack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Babric'
            url = 'https://maven.glass-launcher.net/babric'
        }
        maven {
            name = 'SignalumMavenInfrastructure'
            url = 'https://maven.thesignalumproject.net/infrastructure'
        }
    }
}

// remove what is below, if you are not using local dependencies

// catalyst
include(":catalyst-core")
include(":catalyst-fluids")
include(":catalyst-multiblocks")
include(":catalyst-energy")
include(":catalyst-multipart")
// catalyst

include(":tmb")
include(":btwaila")
include(":dragonfly")
include(":vintage-questing")

// catalyst
project(":catalyst-core").projectDir = file("${rootProject.projectDir}/../catalyst/core")
project(":catalyst-fluids").projectDir = file("${rootProject.projectDir}/../catalyst/fluids")
project(":catalyst-multiblocks").projectDir = file("${rootProject.projectDir}/../catalyst/multiblocks")
project(":catalyst-energy").projectDir = file("${rootProject.projectDir}/../catalyst/energy")
project(":catalyst-multipart").projectDir = file("${rootProject.projectDir}/../catalyst/multipart")
// catalyst

project(":tmb").projectDir = file("${rootProject.projectDir}/../tmb")
project(":btwaila").projectDir = file("${rootProject.projectDir}/../btwaila")
project(":dragonfly").projectDir = file("${rootProject.projectDir}/../dragonfly")
project(":vintage-questing").projectDir = file("${rootProject.projectDir}/../vintage-questing")