pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Babric'
            url = 'https://maven.glass-launcher.net/babric'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}


include(":catalyst")
include(":core")
include(":multiblocks")
include(":multipart")
include(":ami")
//include(":buildcraft")
//include(":nyalib")
//include(":nyalib:buildSrc")
//include(":base")

project(":catalyst").projectDir = file("${rootProject.projectDir}/../catalyst")
project(":core").projectDir = file("${rootProject.projectDir}/../catalyst/core")
project(":multiblocks").projectDir = file("${rootProject.projectDir}/../catalyst/multiblocks")
project(":multipart").projectDir = file("${rootProject.projectDir}/../catalyst/multipart")
project(":ami").projectDir = file("${rootProject.projectDir}/../always-more-items")
//project(":buildcraft").projectDir = file("${rootProject.projectDir}/../Buildcraft")
//project(":nyalib").projectDir = file("${rootProject.projectDir}/../nyalib")
//project(":nyalib:buildSrc").projectDir = file("${rootProject.projectDir}/../nyalib/buildSrc")
//project(":base").projectDir = file("${rootProject.projectDir}/../nyalib/nyalib-base")