pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        maven {
            name = 'Jitpack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Babric'
            url = 'https://maven.glass-launcher.net/babric'
        }
        maven {
            name = 'Quilt'
            url = 'https://maven.quiltmc.org/repository/release'
        }
    }
}

include(":catalyst")
include(":catalyst:energy")
include(":catalyst:fluids")
include(":catalyst:multipart")
include(":btwaila")
include(":tmb")

project(":catalyst").projectDir = file("${rootProject.projectDir}/../catalyst")
project(":catalyst:energy").projectDir = file("${project(":catalyst").projectDir}/energy")
project(":catalyst:fluids").projectDir = file("${project(":catalyst").projectDir}/fluids")
project(":catalyst:multipart").projectDir = file("${project(":catalyst").projectDir}/multipart")
project(":btwaila").projectDir = file("${rootProject.projectDir}/../BTWaila")
project(":tmb").projectDir = file("${rootProject.projectDir}/../TMB")